import { useTexture } from '@react-three/drei';
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/card.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Card(props) {
  const texture =  useTexture("/textures/" + props.url);

  const { nodes, materials } = useGLTF('/models/card.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.109, 1.438]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']}>
            <meshStandardMaterial map={texture}/>
        </mesh>
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/card.glb')
